### ISSUE TITLE
Neverending test if OOM error thrown

### ISSUE THREAD

**Issue by poneill00** [galan/plunger#29]
Hi,

it looks like a plunger test will run forever if the underlying flow throws an OOM exception.
I was running a flow containing a HashJoin where I had accidentally placed the larger pipe on the RHS, running a plunger test over this flow resulted in a test that would never complete (no error thrown)

If I switched the order of the pipes, the test ran as expected, so assuming the flow is dying but not notifying Plunger.

Thanks,
Paul

**Comment by galan** [comment]
I don't understand your question. Maybe you can provide some examples?

**Comment by poneill00** [comment]
apologies, somehow this got opened against the wrong Plunger project :)

disregard!
